version: '2.3'

services:
  rcssserver3d:
    image: parthjindal/rcssserver3d:latest
    environment: 
      SERVER_PORT: "${SERVER_PORT}"
      AGENT_PORT: "${AGENT_PORT}"
    ports: 
    - "${AGENT_PORT}:${AGENT_PORT}"
    - "${SERVER_PORT}:${SERVER_PORT}"
    command: ["--agent-port","${AGENT_PORT}","--server-port","${SERVER_PORT}"]